export const MENSAGENS = {
    // Agendamentos
    ADICIONAR_AGENDAMENTO: "Agendamento adicionado com sucesso!",
    ERRO_ADICIONAR_AGENDAMENTO: "Erro ao adicionar agendamento!",
    EDITAR_AGENDAMENTO: "Agendamento editado com sucesso!",
    ERRO_EDITAR_AGENDAMENTO: "Erro ao editar agendamento!",
    DELETAR_AGENDAMENTO: "Agendamento excluído!",
    ERRO_DELETAR_AGENDAMENTO: "Erro ao excluir agendamento!",
    
    // Caixa
    ADICIONAR_VENDA: "Venda adicionada com sucesso!",
    ERRO_ADICIONAR_VENDA: "Erro ao adicionar venda!",
    FECHAR_CAIXA: "Fechamento de caixa concluído com sucesso!",
    ERRO_FECHAR_CAIXA: "Erro no fechamento de caixa!",
    
    // Serviço da tela de Serviços
    ADICIONAR_SERVICO: "Serviço adicionado com sucesso!",
    ERRO_ADICIONAR_SERVICO: "Erro ao adicionar Serviço!",
    EDITAR_SERVICO: "Serviço editado com sucesso!",
    ERRO_EDITAR_SERVICO: "Erro ao editar Serviço!",
    DELETAR_SERVICO: "Serviço excluído!",
    ERRO_DELETAR_SERVICO: "Erro ao excluir Serviço!",

    // Produto da tela de Serviços
    PRODUTO_CADASTRADO_SUCESSO: "Produto cadastrado com sucesso!",
    ERRO_CADASTRO_PRODUTO: "Erro ao cadastrar produto!",
    EDITAR_PRODUTO: "Produto editado com sucesso!",
    ERRO_CADASTRADO_PRODUTO: "Erro ao editar produto!",
    DELETAR_PRODUTO: "Produto excluído!",
    ERRO_DELETAR_PRODUTO: "Erro ao excluir produto!",
    
    // Promoções da tela de Serviços

    
    CADASTRO_SUCESSO: "Cadastro realizado com sucesso!",
}